### ISSUE TITLE
HTTP 302 Found for .sublime-package asset hosted on GitHub

### ISSUE THREAD

**Issue by blake-regalia** [wbond/package_control_channel#7374] opened 2018-11-29 19:11 UTC
Following @wbond 's helpful instructions, after my package is built via CI it gets posted to GitHub's hosted release service which yields a stable URL, e.g., `https://github.com/blake-regalia/linked-data.syntaxes/releases/download/v0.4.3/LinkedData.sublime-package`. Since GitHub is using an AWS' S3 service to host the actual file, this URL returns an HTTP 302 (temporary redirect) to the S3 object URL. This is technically correct since the S3 object URL may change depending on availability or content-delivery logistics while the GitHub URL remains stable. However, the package control bot considers this an invalid response code and rejects my PR; please [see this here](https://github.com/wbond/package_control_channel/pull/7345#issuecomment-435567570). 

I am wondering if this was a deliberate choice for the package control bot? I do not see a problem with resolving a single 302 redirect and I do not have control over how GitHub hosts its release assets, I am simply using only the free option I know of to host my open-source project build. Do I need to find another way around this?

**Comment by FichteFoll** [comment] 2018-11-29 19:36
FYI, the code running the bot is located here: https://github.com/wbond/packagecontrol.io/blob/master/app/lib/run_repo_tests.py

Most notably, it includes code from two separate projects (including Package Control itself for downloading). I suspect the operation to fail [here](https://github.com/wbond/packagecontrol.io/blob/7fc6e9e605420f2da96245a157acc2386376a9cf/app/lib/run_repo_tests.py#L109) at `manager.fetch` when using `urllib` to download the file as that doesn't handle redirects to my knowledge.

**Comment by FichteFoll** [comment] 2018-11-29 19:44
[This](https://github.com/wbond/package_control/blob/db53090bd0920ca2c58ef27f0361a4d7b096df0e/package_control/downloaders/urllib_downloader.py#L193) is where the error string comes from, most likely, and In [`setup_opener`](https://github.com/wbond/package_control/blob/db53090bd0920ca2c58ef27f0361a4d7b096df0e/package_control/downloaders/urllib_downloader.py#L257) the `HTTPRedirectHandler` class is *not* included.

However, the download setup with all the required proxy stuff and certificate checking is out of my expertise, so probably something @wbond himself needs to address. Either way, this would seem to be an issue with PC itself, not the channel.

**Comment by braver** [comment] 2020-12-13 19:00
Since there is an issue opened for package control (ie. not the channel), and [a work around has been found](https://github.com/wbond/package_control_channel/pull/7345#issuecomment-471786161), I'm going to close this particular issue.

**Closed by braver** 2020-12-13 19:00 UTC

**Comment by rwols** [comment] 2020-12-13 19:06
I don't consider this fixed and still a serious issue. If you run a GitHub action that produces artifacts, then the browser URL for those artifacts are *always* going to point to some Amazon S3 storage location with a HTTP 302 code. This means any such method for producing build artifacts is broken right now.

**Comment by braver** [comment] 2020-12-13 20:09
Sure, but is it a channel issue? It seems like the issue is also covered here: https://github.com/wbond/package_control/issues/1416

**Comment by rwols** [comment] 2020-12-13 20:11
Fair point 👍
